#!/usr/bin/env bash
# This script retrieves DNS information for subdomains

# Function to get subdomain information
function get_subdomain_info() {
  local domain=$1
  local subdomain=$2
  if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
      result=$(dig +short "$sub.$domain" | awk 'NR==1 {print}')
      if [ -n "$result" ]; then
        echo "The subdomain $sub is an A record and points to $result"
      else
        echo "The subdomain $sub does not exist or has no A record"
      fi
    done
  else
    result=$(dig +short "$subdomain.$domain" | awk 'NR==1 {print}')
    if [ -n "$result" ]; then
      echo "The subdomain $subdomain is an A record and points to $result"
    else
      echo "The subdomain $subdomain does not exist or has no A record"
    fi
  fi
}

# Validate the number of arguments
if [ $# -lt 1 ]; then
  echo "Usage: $0 domain [subdomain]"
  exit 1
fi

# Call the function with the provided arguments
get_subdomain_info "$1" "$2"

