#!/usr/bin/env bash
# Setting up server to curl port 80 with no issues
apt-get update && apt-get -y install nginx
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen [::]:80;/' /etc/nginx/sites-available/default
service nginx restart
