#!/usr/bin/env bash
# Install Nginx and configure it to listen on port 80
apt-get update
apt-get install -y nginx
sed -i 's/listen 80 default_server;/listen 80 default_server;\nlisten [::]:80 default_server;/' /etc/nginx/sites-available/default
service nginx start
